openapi: 3.0.3
info:
  contact:
    email: kwatzal@gmail.com
  description: This is the API to retrieve information about me and my career so far.
  title: CV
  version: 1.0.0
servers:
- url: http://localhost:8080/api
tags:
- description: Information about me personally
  name: personal
- description: My previous career path
  name: career
- description: The schools and universities I've attended
  name: education
paths:
  /personal:
    get:
      description: General information and things to know about me
      operationId: getPersonalInformation
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PersonalInformation"
          description: Retrieved personal information
        "500":
          description: An unexpected error has occurred
      tags:
      - personal
      x-accepts:
      - application/json
      x-tags:
      - tag: personal
  /career:
    get:
      description: The career path until today
      operationId: getCareerPath
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CareerPath"
          description: Career path until today
        "500":
          description: An unexpected error has occurred
      tags:
      - career
      x-accepts:
      - application/json
      x-tags:
      - tag: career
  /education:
    get:
      description: The schools and universities I've attended
      operationId: getEducationPath
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EducationPath"
          description: Schools and universities I've attended
        "500":
          description: An unexpected error has occurred
      tags:
      - education
      x-accepts:
      - application/json
      x-tags:
      - tag: education
components:
  schemas:
    PersonalInformation:
      example:
        firstName: Max
        lastName: Mustermann
        phoneNumber: "+43618999997"
        originalFrom:
          country: country
          city: city
        languages:
        - English
        - English
        currentlyLivingIn:
          country: country
          city: city
        interests:
        - Writing OpenAPI specs
        - Writing OpenAPI specs
        age: 33
        email: sample@email.com
      properties:
        firstName:
          example: Max
          type: string
        lastName:
          example: Mustermann
          type: string
        age:
          example: 33
          format: int32
          minimum: 0
          type: integer
        email:
          example: sample@email.com
          type: string
        phoneNumber:
          example: "+43618999997"
          type: string
        originalFrom:
          $ref: "#/components/schemas/City"
        currentlyLivingIn:
          $ref: "#/components/schemas/City"
        languages:
          items:
            example: English
            type: string
          type: array
        interests:
          items:
            example: Writing OpenAPI specs
            type: string
          type: array
      required:
      - age
      - currentlyLivingIn
      - email
      - firstName
      - interests
      - languages
      - lastName
      type: object
    City:
      example:
        country: country
        city: city
      properties:
        country:
          type: string
        city:
          type: string
      required:
      - city
      - country
      type: object
    CareerPath:
      items:
        $ref: "#/components/schemas/CareerItem"
      type: array
    CareerItem:
      example:
        start: 0026-05-24
        company:
          amountOfEmployees: 0
          city:
            country: country
            city: city
          name: Test Company LLC
          branch: Fiction
        end: 0037-04-22
        jobDescription: Backend Developer
        tasks: Writing OpenAPI specifications
      properties:
        company:
          $ref: "#/components/schemas/Company"
        start:
          description: Date in format dd-MM-yyyy
          example: 0026-05-24
          format: date
          type: string
        end:
          description: Date in format dd-MM-yyyy
          example: 0037-04-22
          format: date
          type: string
        jobDescription:
          example: Backend Developer
          type: string
        tasks:
          example: Writing OpenAPI specifications
          type: string
      required:
      - company
      - jobDescription
      - start
      - tasks
      type: object
    Company:
      example:
        amountOfEmployees: 0
        city:
          country: country
          city: city
        name: Test Company LLC
        branch: Fiction
      properties:
        name:
          example: Test Company LLC
          type: string
        branch:
          example: Fiction
          type: string
        city:
          $ref: "#/components/schemas/City"
        amountOfEmployees:
          description: Rough estimation of the amount of employees
          type: integer
      required:
      - amountOfEmployees
      - branch
      - city
      - name
      type: object
    EducationPath:
      items:
        $ref: "#/components/schemas/EducationItem"
      type: array
    EducationItem:
      example:
        city:
          country: country
          city: city
        educationType: ELEMENTARY_SCHOOL
        start: 0037-04-22
        degree: Bachelor of Science
        description: description
        end: 0037-04-22
        schoolName: Making people smart
      properties:
        schoolName:
          example: Making people smart
          type: string
        city:
          $ref: "#/components/schemas/City"
        start:
          description: Date in format dd-MM-yyyy
          example: 0037-04-22
          format: date
          type: string
        end:
          description: |
            Date in format dd-MM-yyyy. In case this field is missing it indicates that I am still
            attending this institution.
          example: 0037-04-22
          format: date
          type: string
        degree:
          example: Bachelor of Science
          type: string
        description:
          description: What I've learned during that time
          type: string
        educationType:
          enum:
          - ELEMENTARY_SCHOOL
          - SECONDARY_SCHOOL
          - COLLEGE
          - UNIVERSITY
          type: string
      required:
      - city
      - degree
      - educationType
      - schoolName
      - start
      type: object
  securitySchemes:
    petstore_auth:
      flows:
        implicit:
          authorizationUrl: https://petstore3.swagger.io/oauth/authorize
          scopes:
            write:pets: modify pets in your account
            read:pets: read your pets
      type: oauth2
    api_key:
      in: header
      name: api_key
      type: apiKey
